services:
  api:
    build: nyanlook_api
    container_name: nyanlook_api
    env_file: nyanlook_api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./nyanlook_api/api:/app/api
      - ./nyanlook_api/requirements.txt:/app/requirements.txt:ro
    depends_on:
      - kvrocks

  kvrocks:
    image: apache/kvrocks:latest
    container_name: nyanlook_kvrocks
    ports:
      - "6666:6666"
    volumes:
      - kvrocks-data:/var/lib/kvrocks

  web:
    build: nyanlook_web
    container_name: nyanlook_web
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  kvrocks-data:
