services:
  api:
    build: api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api/api:/app/api
      - ./api/requirements.txt:/app/requirements.txt:ro
    environment:
      - KVROCKS_HOST=kvrocks
      - KVROCKS_PORT=6666
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - kvrocks

  kvrocks:
    image: apache/kvrocks:latest
    container_name: kvrocks
    ports:
      - "6666:6666"
    volumes:
      - kvrocks-data:/var/lib/kvrocks

volumes:
  kvrocks-data:
